env: TRAVIS=true
dist: bionic
language: python
python:
- "3.10"
- "3.11"
install:
  - pip install -r requirements.txt
script: pytest
jobs:
    include:
        - stage: deploy
          provider: pypi
          distributions: sdist bdist_wheel
          username: __token__
          password:
          secure: I+EypsFJW3Nhk+3TVnA5Wt7xZuMV/8GpDLbRcYCVoily/ybX144vI4PRFqpOwEyW4JEoSpAaFBmrOTgZNeNcR9fFNKMPCF2c+N5yp+OsA+ETDTTJ5ga+bJ+45+9Vszl7cyZItlNZ0VTjfDz69rwudv0T98Co463wtRDynjLVvimx6DK6SRJCmp+vtLhj/22TzstI24xp+TtuKh6pAP+XzIjD8iLMwskLCpaqaMxAPZ27KVygw8z+m6yqIi/DHGm4aAocCxqDCeINOWKu1nRNqoWFsZPhc6Bp5SYcq5zWHpOE9J/D4CLO9pN6TNsxPuudE4pGaGX6/WOmHsvHdP5BCvUs2yG8dULM3UBXmy7aMzZ95XYIjTpQDg0lxxptEC+8LGos9+XoDbDM+XaYTNWknnv8qQ13mq99Mq7R3JN9RNY/+NMlAq0PSNYMz0G2FGc8urJiO6egonuqgsWjHUZkAESr2JXjdIaRfTOfS8SKu6xIx3oz1KCoLk0ct47zyvoe0cVEMx51byvGipEizYktfyP0AXVup3Obd1Xinq2W5fBNQ/QOxWzIyJmQ3ZaRDLXoaW3oDEprZgLPKPgxt7Dz3To/H0PWupwSdPe9V8CLVHvHHXHteEhf2BVnlQx6MNNdANERkKbImdAtfPb6RK0UtA89sgUFV1azg8YwkdgPTOg=iwm+7EVhYS8gml8So3WQH5IfipUVrQhthGMerOY=
          on:
            tags: true
            repo: time-link/timelink-py
            branch: main

