os: linux
dist: bionic
language: python
env: TRAVIS=true
python:
- '3.10'
- '3.11'
install:
- pip install -r requirements.txt
script: pytest

deploy:
  provider: pypi
  edge: true
  skip_existing: true
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: QkybuUGfD7UgciEGMwjncEGaGaF91zSjERpKlKPohDnWRs5r3mBVNNGYwKt8QM5Wcb6DDLys1xkCxZ1p9WG+yEUW+47fyt57HvldNjFaN056eplL5uGG5Y2OQAHV5JN2gXAv3xhPRG5ZJ7rVKlu9HjfixowqpIZNkLh55lJNGzD3/dhn32qLroNV7yU+uRaWTEPvwNRv1Fe/kg32j7bAsQhRFO5FZKVXqphM1obR53i1Q65YwfkUeEYFLqJSjN9W//Hz6LZoEkT9pvKcs9dNQ07xi9eI8N1z5++D6yjcgRR8qqXBUKFv/Bxn1YwR07bcALRuULl6fDhSRtqmt8UUJhkhTnifAn9YL1IyLMaHJLozhIVc+dOvKGXVNmS1OxkPklqBvHgj1M2n6CITTJpNDOGMdhe/XFAOXE4e8qOehoTNy4w3suLSmHSF/eThauynGN/SyHlrfuCKjASkqVwtn0amPo69tUVdWxlxB42IB71nxGxBJwnU3gPBSPPKZk9dJcQMPqgz7X61pmhR9fgBKah4NQ6sBKOS9/W+q2W65zwS1ELpc9E1/WKOHkaUTFa5ha13GXhITmopMS1P1m72KD6Bi6up5vKV5OaI9Xjo007crMhOwyqoWDmgLy0SuB5gkz6tx2WXVFGLVCIL84YseTDgAghrHf3Wg7JWQs93h/0=
  on:
    python: '3.10'
    branch: main
    tags: true

