"""Add blinks table for persistent rids

Revision ID: 36cdd078f890
Revises: 48dd68d06c60
Create Date: 2024-11-30 21:00:23.413029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36cdd078f890'
down_revision: Union[str, None] = '48dd68d06c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blinks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rid', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('rule', sa.String(length=4096), nullable=False),
    sa.Column('status', sa.Enum('UNLINKED', 'AUTOMATIC', 'SOURCE', 'MANUAL', 'MHK', 'N', 'INVALID', name='linkstatus'), nullable=False),
    sa.Column('aregister', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['rid'], ['rentities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blinks_entity'), 'blinks', ['entity'], unique=False)
    op.create_index(op.f('ix_blinks_rid'), 'blinks', ['rid'], unique=False)
    op.create_index(op.f('ix_blinks_source'), 'blinks', ['source'], unique=False)
    op.drop_table('rgeoentities')
    op.drop_table('robjects')
    op.drop_table('rpersons')
    op.drop_table('goods')
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'entities', ['entity'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'entities', ['entity'], ['id'], ondelete='SET NULL')
    op.create_table('goods',
    sa.Column('description', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('loc', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpersons',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('sex', sa.VARCHAR(), nullable=True),
    sa.Column('sname', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['rentities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robjects',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('sname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('the_type', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['rentities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rgeoentities',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('sname', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['rentities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_blinks_source'), table_name='blinks')
    op.drop_index(op.f('ix_blinks_rid'), table_name='blinks')
    op.drop_index(op.f('ix_blinks_entity'), table_name='blinks')
    op.drop_table('blinks')
    # ### end Alembic commands ###
